# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cs_boss_battle.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import dgame_define_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cs_boss_battle.proto',
  package='CS',
  serialized_pb='\n\x14\x63s_boss_battle.proto\x12\x02\x43S\x1a\x12\x64game_define.proto\"\x18\n\x16GetBossBattleStatusReq\"[\n\x16GetBossBattleStatusRsp\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\x15\n\rtoday_boss_id\x18\x02 \x01(\r\x12\x1a\n\x12left_challenge_num\x18\x03 \x01(\r\"8\n\x12StartBossBattleReq\x12\x0f\n\x07\x62oss_id\x18\x01 \x01(\r\x12\x11\n\tdifficult\x18\x02 \x01(\r\"@\n\x12StartBossBattleRsp\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\x1a\n\x12left_challenge_num\x18\x02 \x01(\r\"\"\n\x10\x45ndBossBattleReq\x12\x0e\n\x06is_win\x18\x01 \x01(\x08\"T\n\x10\x45ndBossBattleRsp\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\x30\n\rgift_bag_item\x18\x02 \x01(\x0b\x32\x19.dgame.ExtractGiftBagItem')




_GETBOSSBATTLESTATUSREQ = _descriptor.Descriptor(
  name='GetBossBattleStatusReq',
  full_name='CS.GetBossBattleStatusReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=48,
  serialized_end=72,
)


_GETBOSSBATTLESTATUSRSP = _descriptor.Descriptor(
  name='GetBossBattleStatusRsp',
  full_name='CS.GetBossBattleStatusRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='CS.GetBossBattleStatusRsp.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='today_boss_id', full_name='CS.GetBossBattleStatusRsp.today_boss_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='left_challenge_num', full_name='CS.GetBossBattleStatusRsp.left_challenge_num', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=74,
  serialized_end=165,
)


_STARTBOSSBATTLEREQ = _descriptor.Descriptor(
  name='StartBossBattleReq',
  full_name='CS.StartBossBattleReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='boss_id', full_name='CS.StartBossBattleReq.boss_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='difficult', full_name='CS.StartBossBattleReq.difficult', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=167,
  serialized_end=223,
)


_STARTBOSSBATTLERSP = _descriptor.Descriptor(
  name='StartBossBattleRsp',
  full_name='CS.StartBossBattleRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='CS.StartBossBattleRsp.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='left_challenge_num', full_name='CS.StartBossBattleRsp.left_challenge_num', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=225,
  serialized_end=289,
)


_ENDBOSSBATTLEREQ = _descriptor.Descriptor(
  name='EndBossBattleReq',
  full_name='CS.EndBossBattleReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_win', full_name='CS.EndBossBattleReq.is_win', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=291,
  serialized_end=325,
)


_ENDBOSSBATTLERSP = _descriptor.Descriptor(
  name='EndBossBattleRsp',
  full_name='CS.EndBossBattleRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='CS.EndBossBattleRsp.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gift_bag_item', full_name='CS.EndBossBattleRsp.gift_bag_item', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=327,
  serialized_end=411,
)

_ENDBOSSBATTLERSP.fields_by_name['gift_bag_item'].message_type = dgame_define_pb2._EXTRACTGIFTBAGITEM
DESCRIPTOR.message_types_by_name['GetBossBattleStatusReq'] = _GETBOSSBATTLESTATUSREQ
DESCRIPTOR.message_types_by_name['GetBossBattleStatusRsp'] = _GETBOSSBATTLESTATUSRSP
DESCRIPTOR.message_types_by_name['StartBossBattleReq'] = _STARTBOSSBATTLEREQ
DESCRIPTOR.message_types_by_name['StartBossBattleRsp'] = _STARTBOSSBATTLERSP
DESCRIPTOR.message_types_by_name['EndBossBattleReq'] = _ENDBOSSBATTLEREQ
DESCRIPTOR.message_types_by_name['EndBossBattleRsp'] = _ENDBOSSBATTLERSP

class GetBossBattleStatusReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETBOSSBATTLESTATUSREQ

  # @@protoc_insertion_point(class_scope:CS.GetBossBattleStatusReq)

class GetBossBattleStatusRsp(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETBOSSBATTLESTATUSRSP

  # @@protoc_insertion_point(class_scope:CS.GetBossBattleStatusRsp)

class StartBossBattleReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STARTBOSSBATTLEREQ

  # @@protoc_insertion_point(class_scope:CS.StartBossBattleReq)

class StartBossBattleRsp(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STARTBOSSBATTLERSP

  # @@protoc_insertion_point(class_scope:CS.StartBossBattleRsp)

class EndBossBattleReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ENDBOSSBATTLEREQ

  # @@protoc_insertion_point(class_scope:CS.EndBossBattleReq)

class EndBossBattleRsp(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ENDBOSSBATTLERSP

  # @@protoc_insertion_point(class_scope:CS.EndBossBattleRsp)


# @@protoc_insertion_point(module_scope)
