# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cs_money_tree.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import dgame_define_pb2 as dgame__define__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cs_money_tree.proto',
  package='CS',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x63s_money_tree.proto\x12\x02\x43S\x1a\x12\x64game_define.proto\"*\n\x18GetMoneyTreeLeftTimesReq\x12\x0e\n\x06unused\x18\x01 \x01(\r\"S\n\x18GetMoneyTreeLeftTimesRsp\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\x12\n\nleft_times\x18\x02 \x01(\r\x12\x13\n\x0btotal_times\x18\x03 \x01(\r\"#\n\x11ShakeMoneyTreeReq\x12\x0e\n\x06unused\x18\x01 \x01(\r\"\x83\x01\n\x11ShakeMoneyTreeRsp\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\x14\n\x0cget_gold_num\x18\x02 \x01(\r\x12\x1a\n\x12new_total_gold_num\x18\x03 \x01(\r\x12\r\n\x05times\x18\x04 \x01(\r\x12\x1d\n\x15new_total_diamond_num\x18\x05 \x01(\r\"+\n\x19\x43ontinueShakeMoneyTreeReq\x12\x0e\n\x06unused\x18\x01 \x01(\r\"\x96\x01\n\x19\x43ontinueShakeMoneyTreeRsp\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12.\n\rget_gold_list\x18\x02 \x03(\x0b\x32\x17.dgame.MoneyTreeGetGold\x12\x1a\n\x12new_total_gold_num\x18\x03 \x01(\r\x12\x1d\n\x15new_total_diamond_num\x18\x04 \x01(\r\"\x1d\n\x1bGetShakeMoneyTreeHistoryReq\"]\n\x1bGetShakeMoneyTreeHistoryRsp\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12.\n\rget_gold_list\x18\x02 \x03(\x0b\x32\x17.dgame.MoneyTreeGetGoldb\x06proto3'
  ,
  dependencies=[dgame__define__pb2.DESCRIPTOR,])




_GETMONEYTREELEFTTIMESREQ = _descriptor.Descriptor(
  name='GetMoneyTreeLeftTimesReq',
  full_name='CS.GetMoneyTreeLeftTimesReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='unused', full_name='CS.GetMoneyTreeLeftTimesReq.unused', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=89,
)


_GETMONEYTREELEFTTIMESRSP = _descriptor.Descriptor(
  name='GetMoneyTreeLeftTimesRsp',
  full_name='CS.GetMoneyTreeLeftTimesRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='CS.GetMoneyTreeLeftTimesRsp.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='left_times', full_name='CS.GetMoneyTreeLeftTimesRsp.left_times', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_times', full_name='CS.GetMoneyTreeLeftTimesRsp.total_times', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=174,
)


_SHAKEMONEYTREEREQ = _descriptor.Descriptor(
  name='ShakeMoneyTreeReq',
  full_name='CS.ShakeMoneyTreeReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='unused', full_name='CS.ShakeMoneyTreeReq.unused', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=211,
)


_SHAKEMONEYTREERSP = _descriptor.Descriptor(
  name='ShakeMoneyTreeRsp',
  full_name='CS.ShakeMoneyTreeRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='CS.ShakeMoneyTreeRsp.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='get_gold_num', full_name='CS.ShakeMoneyTreeRsp.get_gold_num', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='new_total_gold_num', full_name='CS.ShakeMoneyTreeRsp.new_total_gold_num', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='times', full_name='CS.ShakeMoneyTreeRsp.times', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='new_total_diamond_num', full_name='CS.ShakeMoneyTreeRsp.new_total_diamond_num', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=345,
)


_CONTINUESHAKEMONEYTREEREQ = _descriptor.Descriptor(
  name='ContinueShakeMoneyTreeReq',
  full_name='CS.ContinueShakeMoneyTreeReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='unused', full_name='CS.ContinueShakeMoneyTreeReq.unused', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=347,
  serialized_end=390,
)


_CONTINUESHAKEMONEYTREERSP = _descriptor.Descriptor(
  name='ContinueShakeMoneyTreeRsp',
  full_name='CS.ContinueShakeMoneyTreeRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='CS.ContinueShakeMoneyTreeRsp.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='get_gold_list', full_name='CS.ContinueShakeMoneyTreeRsp.get_gold_list', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='new_total_gold_num', full_name='CS.ContinueShakeMoneyTreeRsp.new_total_gold_num', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='new_total_diamond_num', full_name='CS.ContinueShakeMoneyTreeRsp.new_total_diamond_num', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=393,
  serialized_end=543,
)


_GETSHAKEMONEYTREEHISTORYREQ = _descriptor.Descriptor(
  name='GetShakeMoneyTreeHistoryReq',
  full_name='CS.GetShakeMoneyTreeHistoryReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=545,
  serialized_end=574,
)


_GETSHAKEMONEYTREEHISTORYRSP = _descriptor.Descriptor(
  name='GetShakeMoneyTreeHistoryRsp',
  full_name='CS.GetShakeMoneyTreeHistoryRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='CS.GetShakeMoneyTreeHistoryRsp.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='get_gold_list', full_name='CS.GetShakeMoneyTreeHistoryRsp.get_gold_list', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=576,
  serialized_end=669,
)

_CONTINUESHAKEMONEYTREERSP.fields_by_name['get_gold_list'].message_type = dgame__define__pb2._MONEYTREEGETGOLD
_GETSHAKEMONEYTREEHISTORYRSP.fields_by_name['get_gold_list'].message_type = dgame__define__pb2._MONEYTREEGETGOLD
DESCRIPTOR.message_types_by_name['GetMoneyTreeLeftTimesReq'] = _GETMONEYTREELEFTTIMESREQ
DESCRIPTOR.message_types_by_name['GetMoneyTreeLeftTimesRsp'] = _GETMONEYTREELEFTTIMESRSP
DESCRIPTOR.message_types_by_name['ShakeMoneyTreeReq'] = _SHAKEMONEYTREEREQ
DESCRIPTOR.message_types_by_name['ShakeMoneyTreeRsp'] = _SHAKEMONEYTREERSP
DESCRIPTOR.message_types_by_name['ContinueShakeMoneyTreeReq'] = _CONTINUESHAKEMONEYTREEREQ
DESCRIPTOR.message_types_by_name['ContinueShakeMoneyTreeRsp'] = _CONTINUESHAKEMONEYTREERSP
DESCRIPTOR.message_types_by_name['GetShakeMoneyTreeHistoryReq'] = _GETSHAKEMONEYTREEHISTORYREQ
DESCRIPTOR.message_types_by_name['GetShakeMoneyTreeHistoryRsp'] = _GETSHAKEMONEYTREEHISTORYRSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetMoneyTreeLeftTimesReq = _reflection.GeneratedProtocolMessageType('GetMoneyTreeLeftTimesReq', (_message.Message,), {
  'DESCRIPTOR' : _GETMONEYTREELEFTTIMESREQ,
  '__module__' : 'cs_money_tree_pb2'
  # @@protoc_insertion_point(class_scope:CS.GetMoneyTreeLeftTimesReq)
  })
_sym_db.RegisterMessage(GetMoneyTreeLeftTimesReq)

GetMoneyTreeLeftTimesRsp = _reflection.GeneratedProtocolMessageType('GetMoneyTreeLeftTimesRsp', (_message.Message,), {
  'DESCRIPTOR' : _GETMONEYTREELEFTTIMESRSP,
  '__module__' : 'cs_money_tree_pb2'
  # @@protoc_insertion_point(class_scope:CS.GetMoneyTreeLeftTimesRsp)
  })
_sym_db.RegisterMessage(GetMoneyTreeLeftTimesRsp)

ShakeMoneyTreeReq = _reflection.GeneratedProtocolMessageType('ShakeMoneyTreeReq', (_message.Message,), {
  'DESCRIPTOR' : _SHAKEMONEYTREEREQ,
  '__module__' : 'cs_money_tree_pb2'
  # @@protoc_insertion_point(class_scope:CS.ShakeMoneyTreeReq)
  })
_sym_db.RegisterMessage(ShakeMoneyTreeReq)

ShakeMoneyTreeRsp = _reflection.GeneratedProtocolMessageType('ShakeMoneyTreeRsp', (_message.Message,), {
  'DESCRIPTOR' : _SHAKEMONEYTREERSP,
  '__module__' : 'cs_money_tree_pb2'
  # @@protoc_insertion_point(class_scope:CS.ShakeMoneyTreeRsp)
  })
_sym_db.RegisterMessage(ShakeMoneyTreeRsp)

ContinueShakeMoneyTreeReq = _reflection.GeneratedProtocolMessageType('ContinueShakeMoneyTreeReq', (_message.Message,), {
  'DESCRIPTOR' : _CONTINUESHAKEMONEYTREEREQ,
  '__module__' : 'cs_money_tree_pb2'
  # @@protoc_insertion_point(class_scope:CS.ContinueShakeMoneyTreeReq)
  })
_sym_db.RegisterMessage(ContinueShakeMoneyTreeReq)

ContinueShakeMoneyTreeRsp = _reflection.GeneratedProtocolMessageType('ContinueShakeMoneyTreeRsp', (_message.Message,), {
  'DESCRIPTOR' : _CONTINUESHAKEMONEYTREERSP,
  '__module__' : 'cs_money_tree_pb2'
  # @@protoc_insertion_point(class_scope:CS.ContinueShakeMoneyTreeRsp)
  })
_sym_db.RegisterMessage(ContinueShakeMoneyTreeRsp)

GetShakeMoneyTreeHistoryReq = _reflection.GeneratedProtocolMessageType('GetShakeMoneyTreeHistoryReq', (_message.Message,), {
  'DESCRIPTOR' : _GETSHAKEMONEYTREEHISTORYREQ,
  '__module__' : 'cs_money_tree_pb2'
  # @@protoc_insertion_point(class_scope:CS.GetShakeMoneyTreeHistoryReq)
  })
_sym_db.RegisterMessage(GetShakeMoneyTreeHistoryReq)

GetShakeMoneyTreeHistoryRsp = _reflection.GeneratedProtocolMessageType('GetShakeMoneyTreeHistoryRsp', (_message.Message,), {
  'DESCRIPTOR' : _GETSHAKEMONEYTREEHISTORYRSP,
  '__module__' : 'cs_money_tree_pb2'
  # @@protoc_insertion_point(class_scope:CS.GetShakeMoneyTreeHistoryRsp)
  })
_sym_db.RegisterMessage(GetShakeMoneyTreeHistoryRsp)


# @@protoc_insertion_point(module_scope)
