# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cs_stamina.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cs_stamina.proto',
  package='CS',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x63s_stamina.proto\x12\x02\x43S\"\x1f\n\rBuyStaminaReq\x12\x0e\n\x06unused\x18\x01 \x01(\r\"[\n\rBuyStaminaRsp\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\x13\n\x0bnew_stanima\x18\x02 \x01(\r\x12\x10\n\x08new_gold\x18\x03 \x01(\r\x12\x13\n\x0bnew_diamond\x18\x04 \x01(\r\"#\n\x11GetStaminaDataReq\x12\x0e\n\x06unused\x18\x01 \x01(\r\"[\n\x11GetStaminaDataRsp\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\x12\n\nleft_times\x18\x02 \x01(\r\x12\x13\n\x0btotal_times\x18\x03 \x01(\r\x12\r\n\x05price\x18\x04 \x01(\rb\x06proto3'
)




_BUYSTAMINAREQ = _descriptor.Descriptor(
  name='BuyStaminaReq',
  full_name='CS.BuyStaminaReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='unused', full_name='CS.BuyStaminaReq.unused', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=55,
)


_BUYSTAMINARSP = _descriptor.Descriptor(
  name='BuyStaminaRsp',
  full_name='CS.BuyStaminaRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='CS.BuyStaminaRsp.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='new_stanima', full_name='CS.BuyStaminaRsp.new_stanima', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='new_gold', full_name='CS.BuyStaminaRsp.new_gold', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='new_diamond', full_name='CS.BuyStaminaRsp.new_diamond', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=148,
)


_GETSTAMINADATAREQ = _descriptor.Descriptor(
  name='GetStaminaDataReq',
  full_name='CS.GetStaminaDataReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='unused', full_name='CS.GetStaminaDataReq.unused', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=185,
)


_GETSTAMINADATARSP = _descriptor.Descriptor(
  name='GetStaminaDataRsp',
  full_name='CS.GetStaminaDataRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='CS.GetStaminaDataRsp.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='left_times', full_name='CS.GetStaminaDataRsp.left_times', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_times', full_name='CS.GetStaminaDataRsp.total_times', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='CS.GetStaminaDataRsp.price', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=278,
)

DESCRIPTOR.message_types_by_name['BuyStaminaReq'] = _BUYSTAMINAREQ
DESCRIPTOR.message_types_by_name['BuyStaminaRsp'] = _BUYSTAMINARSP
DESCRIPTOR.message_types_by_name['GetStaminaDataReq'] = _GETSTAMINADATAREQ
DESCRIPTOR.message_types_by_name['GetStaminaDataRsp'] = _GETSTAMINADATARSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BuyStaminaReq = _reflection.GeneratedProtocolMessageType('BuyStaminaReq', (_message.Message,), {
  'DESCRIPTOR' : _BUYSTAMINAREQ,
  '__module__' : 'cs_stamina_pb2'
  # @@protoc_insertion_point(class_scope:CS.BuyStaminaReq)
  })
_sym_db.RegisterMessage(BuyStaminaReq)

BuyStaminaRsp = _reflection.GeneratedProtocolMessageType('BuyStaminaRsp', (_message.Message,), {
  'DESCRIPTOR' : _BUYSTAMINARSP,
  '__module__' : 'cs_stamina_pb2'
  # @@protoc_insertion_point(class_scope:CS.BuyStaminaRsp)
  })
_sym_db.RegisterMessage(BuyStaminaRsp)

GetStaminaDataReq = _reflection.GeneratedProtocolMessageType('GetStaminaDataReq', (_message.Message,), {
  'DESCRIPTOR' : _GETSTAMINADATAREQ,
  '__module__' : 'cs_stamina_pb2'
  # @@protoc_insertion_point(class_scope:CS.GetStaminaDataReq)
  })
_sym_db.RegisterMessage(GetStaminaDataReq)

GetStaminaDataRsp = _reflection.GeneratedProtocolMessageType('GetStaminaDataRsp', (_message.Message,), {
  'DESCRIPTOR' : _GETSTAMINADATARSP,
  '__module__' : 'cs_stamina_pb2'
  # @@protoc_insertion_point(class_scope:CS.GetStaminaDataRsp)
  })
_sym_db.RegisterMessage(GetStaminaDataRsp)


# @@protoc_insertion_point(module_scope)
