# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: header.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='header.proto',
  package='protocol',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cheader.proto\x12\x08protocol\"\x9e\x02\n\x06Header\x12\x13\n\x06roleid\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x10\n\x03seq\x18\x02 \x01(\rH\x01\x88\x01\x01\x12\x16\n\tsessionid\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x18\n\x0bre_send_cnt\x18\x04 \x01(\rH\x03\x88\x01\x01\x12\x1a\n\rmsg_full_name\x18\x05 \x01(\tH\x04\x88\x01\x01\x12\x14\n\x07version\x18\x06 \x01(\x04H\x05\x88\x01\x01\x12\x10\n\x03uid\x18\x07 \x01(\x04H\x06\x88\x01\x01\x12\x14\n\x07is_json\x18\x08 \x01(\x08H\x07\x88\x01\x01\x42\t\n\x07_roleidB\x06\n\x04_seqB\x0c\n\n_sessionidB\x0e\n\x0c_re_send_cntB\x10\n\x0e_msg_full_nameB\n\n\x08_versionB\x06\n\x04_uidB\n\n\x08_is_jsonb\x06proto3'
)




_HEADER = _descriptor.Descriptor(
  name='Header',
  full_name='protocol.Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='roleid', full_name='protocol.Header.roleid', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='seq', full_name='protocol.Header.seq', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sessionid', full_name='protocol.Header.sessionid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='re_send_cnt', full_name='protocol.Header.re_send_cnt', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg_full_name', full_name='protocol.Header.msg_full_name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='protocol.Header.version', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uid', full_name='protocol.Header.uid', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_json', full_name='protocol.Header.is_json', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_roleid', full_name='protocol.Header._roleid',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_seq', full_name='protocol.Header._seq',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_sessionid', full_name='protocol.Header._sessionid',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_re_send_cnt', full_name='protocol.Header._re_send_cnt',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_msg_full_name', full_name='protocol.Header._msg_full_name',
      index=4, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_version', full_name='protocol.Header._version',
      index=5, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_uid', full_name='protocol.Header._uid',
      index=6, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_is_json', full_name='protocol.Header._is_json',
      index=7, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=27,
  serialized_end=313,
)

_HEADER.oneofs_by_name['_roleid'].fields.append(
  _HEADER.fields_by_name['roleid'])
_HEADER.fields_by_name['roleid'].containing_oneof = _HEADER.oneofs_by_name['_roleid']
_HEADER.oneofs_by_name['_seq'].fields.append(
  _HEADER.fields_by_name['seq'])
_HEADER.fields_by_name['seq'].containing_oneof = _HEADER.oneofs_by_name['_seq']
_HEADER.oneofs_by_name['_sessionid'].fields.append(
  _HEADER.fields_by_name['sessionid'])
_HEADER.fields_by_name['sessionid'].containing_oneof = _HEADER.oneofs_by_name['_sessionid']
_HEADER.oneofs_by_name['_re_send_cnt'].fields.append(
  _HEADER.fields_by_name['re_send_cnt'])
_HEADER.fields_by_name['re_send_cnt'].containing_oneof = _HEADER.oneofs_by_name['_re_send_cnt']
_HEADER.oneofs_by_name['_msg_full_name'].fields.append(
  _HEADER.fields_by_name['msg_full_name'])
_HEADER.fields_by_name['msg_full_name'].containing_oneof = _HEADER.oneofs_by_name['_msg_full_name']
_HEADER.oneofs_by_name['_version'].fields.append(
  _HEADER.fields_by_name['version'])
_HEADER.fields_by_name['version'].containing_oneof = _HEADER.oneofs_by_name['_version']
_HEADER.oneofs_by_name['_uid'].fields.append(
  _HEADER.fields_by_name['uid'])
_HEADER.fields_by_name['uid'].containing_oneof = _HEADER.oneofs_by_name['_uid']
_HEADER.oneofs_by_name['_is_json'].fields.append(
  _HEADER.fields_by_name['is_json'])
_HEADER.fields_by_name['is_json'].containing_oneof = _HEADER.oneofs_by_name['_is_json']
DESCRIPTOR.message_types_by_name['Header'] = _HEADER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), {
  'DESCRIPTOR' : _HEADER,
  '__module__' : 'header_pb2'
  # @@protoc_insertion_point(class_scope:protocol.Header)
  })
_sym_db.RegisterMessage(Header)


# @@protoc_insertion_point(module_scope)
