# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mail_db.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import cs_mail_pb2 as cs__mail__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mail_db.proto',
  package='dgame',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rmail_db.proto\x12\x05\x64game\x1a\rcs_mail.proto\"f\n\x08MailData\x12\x18\n\x10last_update_time\x18\x01 \x01(\r\x12\x1b\n\x13last_writeback_time\x18\x02 \x01(\r\x12#\n\x0bsystem_mail\x18\x03 \x03(\x0b\x32\x0e.CS.SystemMail\"O\n\x0f\x44\x65letedAnnounce\x12\x10\n\x08mail_gid\x18\x01 \x01(\x04\x12\x15\n\rgenerate_time\x18\x02 \x01(\r\x12\x13\n\x0b\x65xpire_time\x18\x03 \x01(\r\"G\n\x13\x44\x65letedAnnounceData\x12\x30\n\x10\x64\x65leted_announce\x18\x01 \x03(\x0b\x32\x16.dgame.DeletedAnnounce\"F\n\nMailDbData\x12#\n\x0bsystem_mail\x18\x01 \x01(\x0b\x32\x0e.CS.SystemMail\x12\x13\n\x0broleid_list\x18\x02 \x03(\x04\"9\n\x0cTempMailData\x12)\n\x0email_data_list\x18\x01 \x03(\x0b\x32\x11.dgame.MailDbDatab\x06proto3'
  ,
  dependencies=[cs__mail__pb2.DESCRIPTOR,])




_MAILDATA = _descriptor.Descriptor(
  name='MailData',
  full_name='dgame.MailData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='last_update_time', full_name='dgame.MailData.last_update_time', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_writeback_time', full_name='dgame.MailData.last_writeback_time', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='system_mail', full_name='dgame.MailData.system_mail', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=141,
)


_DELETEDANNOUNCE = _descriptor.Descriptor(
  name='DeletedAnnounce',
  full_name='dgame.DeletedAnnounce',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mail_gid', full_name='dgame.DeletedAnnounce.mail_gid', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='generate_time', full_name='dgame.DeletedAnnounce.generate_time', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='expire_time', full_name='dgame.DeletedAnnounce.expire_time', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=222,
)


_DELETEDANNOUNCEDATA = _descriptor.Descriptor(
  name='DeletedAnnounceData',
  full_name='dgame.DeletedAnnounceData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='deleted_announce', full_name='dgame.DeletedAnnounceData.deleted_announce', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=295,
)


_MAILDBDATA = _descriptor.Descriptor(
  name='MailDbData',
  full_name='dgame.MailDbData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='system_mail', full_name='dgame.MailDbData.system_mail', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='roleid_list', full_name='dgame.MailDbData.roleid_list', index=1,
      number=2, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=367,
)


_TEMPMAILDATA = _descriptor.Descriptor(
  name='TempMailData',
  full_name='dgame.TempMailData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mail_data_list', full_name='dgame.TempMailData.mail_data_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=369,
  serialized_end=426,
)

_MAILDATA.fields_by_name['system_mail'].message_type = cs__mail__pb2._SYSTEMMAIL
_DELETEDANNOUNCEDATA.fields_by_name['deleted_announce'].message_type = _DELETEDANNOUNCE
_MAILDBDATA.fields_by_name['system_mail'].message_type = cs__mail__pb2._SYSTEMMAIL
_TEMPMAILDATA.fields_by_name['mail_data_list'].message_type = _MAILDBDATA
DESCRIPTOR.message_types_by_name['MailData'] = _MAILDATA
DESCRIPTOR.message_types_by_name['DeletedAnnounce'] = _DELETEDANNOUNCE
DESCRIPTOR.message_types_by_name['DeletedAnnounceData'] = _DELETEDANNOUNCEDATA
DESCRIPTOR.message_types_by_name['MailDbData'] = _MAILDBDATA
DESCRIPTOR.message_types_by_name['TempMailData'] = _TEMPMAILDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MailData = _reflection.GeneratedProtocolMessageType('MailData', (_message.Message,), {
  'DESCRIPTOR' : _MAILDATA,
  '__module__' : 'mail_db_pb2'
  # @@protoc_insertion_point(class_scope:dgame.MailData)
  })
_sym_db.RegisterMessage(MailData)

DeletedAnnounce = _reflection.GeneratedProtocolMessageType('DeletedAnnounce', (_message.Message,), {
  'DESCRIPTOR' : _DELETEDANNOUNCE,
  '__module__' : 'mail_db_pb2'
  # @@protoc_insertion_point(class_scope:dgame.DeletedAnnounce)
  })
_sym_db.RegisterMessage(DeletedAnnounce)

DeletedAnnounceData = _reflection.GeneratedProtocolMessageType('DeletedAnnounceData', (_message.Message,), {
  'DESCRIPTOR' : _DELETEDANNOUNCEDATA,
  '__module__' : 'mail_db_pb2'
  # @@protoc_insertion_point(class_scope:dgame.DeletedAnnounceData)
  })
_sym_db.RegisterMessage(DeletedAnnounceData)

MailDbData = _reflection.GeneratedProtocolMessageType('MailDbData', (_message.Message,), {
  'DESCRIPTOR' : _MAILDBDATA,
  '__module__' : 'mail_db_pb2'
  # @@protoc_insertion_point(class_scope:dgame.MailDbData)
  })
_sym_db.RegisterMessage(MailDbData)

TempMailData = _reflection.GeneratedProtocolMessageType('TempMailData', (_message.Message,), {
  'DESCRIPTOR' : _TEMPMAILDATA,
  '__module__' : 'mail_db_pb2'
  # @@protoc_insertion_point(class_scope:dgame.TempMailData)
  })
_sym_db.RegisterMessage(TempMailData)


# @@protoc_insertion_point(module_scope)
