# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ss_control.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ss_control.proto',
  package='SS',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10ss_control.proto\x12\x02SS\"\x1c\n\nHotStopReq\x12\x0e\n\x06unused\x18\x01 \x01(\r\"\"\n\x10\x41\x63\x63\x65ssRestartReq\x12\x0e\n\x06unused\x18\x01 \x01(\r\"!\n\x0fReloadConfigReq\x12\x0e\n\x06unused\x18\x01 \x01(\r\"\t\n\x07StopReqb\x06proto3'
)




_HOTSTOPREQ = _descriptor.Descriptor(
  name='HotStopReq',
  full_name='SS.HotStopReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='unused', full_name='SS.HotStopReq.unused', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=52,
)


_ACCESSRESTARTREQ = _descriptor.Descriptor(
  name='AccessRestartReq',
  full_name='SS.AccessRestartReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='unused', full_name='SS.AccessRestartReq.unused', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=88,
)


_RELOADCONFIGREQ = _descriptor.Descriptor(
  name='ReloadConfigReq',
  full_name='SS.ReloadConfigReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='unused', full_name='SS.ReloadConfigReq.unused', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=123,
)


_STOPREQ = _descriptor.Descriptor(
  name='StopReq',
  full_name='SS.StopReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=134,
)

DESCRIPTOR.message_types_by_name['HotStopReq'] = _HOTSTOPREQ
DESCRIPTOR.message_types_by_name['AccessRestartReq'] = _ACCESSRESTARTREQ
DESCRIPTOR.message_types_by_name['ReloadConfigReq'] = _RELOADCONFIGREQ
DESCRIPTOR.message_types_by_name['StopReq'] = _STOPREQ
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HotStopReq = _reflection.GeneratedProtocolMessageType('HotStopReq', (_message.Message,), {
  'DESCRIPTOR' : _HOTSTOPREQ,
  '__module__' : 'ss_control_pb2'
  # @@protoc_insertion_point(class_scope:SS.HotStopReq)
  })
_sym_db.RegisterMessage(HotStopReq)

AccessRestartReq = _reflection.GeneratedProtocolMessageType('AccessRestartReq', (_message.Message,), {
  'DESCRIPTOR' : _ACCESSRESTARTREQ,
  '__module__' : 'ss_control_pb2'
  # @@protoc_insertion_point(class_scope:SS.AccessRestartReq)
  })
_sym_db.RegisterMessage(AccessRestartReq)

ReloadConfigReq = _reflection.GeneratedProtocolMessageType('ReloadConfigReq', (_message.Message,), {
  'DESCRIPTOR' : _RELOADCONFIGREQ,
  '__module__' : 'ss_control_pb2'
  # @@protoc_insertion_point(class_scope:SS.ReloadConfigReq)
  })
_sym_db.RegisterMessage(ReloadConfigReq)

StopReq = _reflection.GeneratedProtocolMessageType('StopReq', (_message.Message,), {
  'DESCRIPTOR' : _STOPREQ,
  '__module__' : 'ss_control_pb2'
  # @@protoc_insertion_point(class_scope:SS.StopReq)
  })
_sym_db.RegisterMessage(StopReq)


# @@protoc_insertion_point(module_scope)
