version: "3.8"
# 单机 RabbitMQ
services:
  rabbit:
    image: rabbitmq:management
    hostname: rabbit
    container_name: "dnmp-rabbitmq"
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456
    volumes:
      - ./data:/var/lib/rabbitmq
